# Generated by Django 3.0.2 on 2020-01-29 18:34

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telnum', models.CharField(max_length=11, unique=True, validators=[users.validators.validate_phonenumber], verbose_name='Phone Number')),
                ('name', models.CharField(max_length=32)),
                ('rec_telnum', models.CharField(blank=True, max_length=11, null=True, validators=[users.validators.validate_phonenumber], verbose_name='Recommender Phone Number')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
