# Generated by Django 3.0.2 on 2020-01-30 18:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rec_telnum',
        ),
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.IntegerField(default=97112563, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rec_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[users.validators.validate_phonenumber], verbose_name='Recommender code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telnum',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, message=''), users.validators.validate_phonenumber], verbose_name='Phone Number'),
        ),
    ]
