# Generated by Django 3.0.2 on 2020-01-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200131_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
